from enum import Enum


class OperationMarker(Enum):
    RAW_INPUT_WRITE = 1
    MODULE_UPDATE = 2
    SELF_GENERATED_THOUGHT = 3
    PREDICTION = 4
    LABEL = 5
    NEUROMODULATION_UPDATE = 6
    INTERNAL_DECISION = 7
    INTERNAL_ACTION_EFFECT = 8
    OUTCOME_EVALUATION = 9
    EXPERIENCE_CANDIDATE = 10
    CONSOLIDATION_CANDIDATE = 11
    CONSOLIDATION_PRESSURE = 12
    SYSTEM_MODE_CHANGE = 13
    MEMORY_WRITE_REVIEW = 14
    MEMORY_DRAFT_WRITTEN = 15
    MEMORY_DRAFT_COMMIT_REVIEW = 16
    MEMORY_COMMITTED = 17
    COMMITTED_DRAFT_OBSERVED = 18
    EXPSM_UPDATE_REVIEW = 19
    MEMORY_UPDATED = 20
    EXPSM_ACTIVATION = 21
    EXPSM_FEEDBACK = 22
    EXPSM_SIMILARITY_OBSERVED = 23
    EXPSM_COMPETITION_OBSERVED = 24
