from enum import Enum


class OperationMarker(Enum):
    RAW_INPUT_WRITE = 1
    MODULE_UPDATE = 2
    SELF_GENERATED_THOUGHT = 3
    PREDICTION = 4
    LABEL = 5
    NEUROMODULATION_UPDATE = 6
    INTERNAL_DECISION = 7
    INTERNAL_ACTION_EFFECT = 8
    OUTCOME_EVALUATION = 9
    EXPERIENCE_CANDIDATE = 10
    CONSOLIDATION_CANDIDATE = 11
    CONSOLIDATION_PRESSURE = 12
    SYSTEM_MODE_CHANGE = 13
    MEMORY_WRITE_REVIEW = 14
    MEMORY_DRAFT_WRITTEN = 15
    MEMORY_DRAFT_COMMIT_REVIEW = 16
    MEMORY_COMMITTED = 17
    COMMITTED_DRAFT_OBSERVED = 18
    EXPSM_UPDATE_REVIEW = 19
    MEMORY_UPDATED = 20
    EXPSM_ACTIVATION = 21
    EXPSM_FEEDBACK = 22
    EXPSM_SIMILARITY_OBSERVED = 23
    EXPSM_COMPETITION_OBSERVED = 24
    EVALUATION_SIGNAL = 25
    EVALUATION_TARGET_OBSERVED = 26
    AKBSM_ASSOCIATION_PROBE = 27
    EXPSM_MECHANISM_SEARCH = 28
    TARGET_SATISFACTION_OBSERVED = 29
    VALUE_FEEDBACK_CANDIDATE = 30
    VALUE_FEEDBACK_REVIEW = 31
    VALUE_FEEDBACK_UPDATED = 32
    DECISION_AUDIT_OBSERVED = 33
    ACTION_GUARD_AUDIT_OBSERVED = 34
    DECISION_CYCLE_SUMMARY = 35
